version: "3.9"

services:
  next:
    build: ./
    volumes:
      - ./src:/opt/app
    ports:
      - "32000:3000"
    command: bash -c "npm install && npm run dev"
    environment:
      - WATCHPACK_POLLING=true
    tty: true